### ISSUE TITLE
[BUG] Error in create a table from a dask_cudf dataframe

### ISSUE THREAD

**Issue by ivenzor** [BlazingDB/pyBlazing#82] opened 2019-10-02 15:40 UTC
I'm trying to create a blazingsql (0.4.3) table based on a dask_cudf dataframe but I'm getting an error:

```
df2=dask_cudf.read_csv(list_of_files)
df2.head()

bc.create_table('test', df2)

AttributeError: 'NoneType' object has no attribute 'table_name'
```

**Comment by aucahuasi** [comment] 2019-10-02 18:42
Hi @ivenzor thanks, let me check if we can reproduce this with our latest version. Also it seems we are in the middle of get better support for our dask integration. I'll get back to you soon! cc @gcca @editaxz @mario21ic @felipeblazing

**Comment by felipeblazing** [comment] 2019-10-02 20:38
Hey there is a PR https://github.com/BlazingDB/blazingdb-ral/pull/162 Tht will address this.
I am going to try and merge it in very soon. Next few hours @ivenzor

**Comment by felipeblazing** [comment] 2019-10-02 20:38
FYI don't try and build it yoruself until its accepted since its several prs over different repos

**Comment by aucahuasi** [comment] 2019-10-02 20:46
Thanks @felipeblazing 
So we will notify you @ivenzor as soon as we have this new release +1

**Comment by ivenzor** [comment] 2019-10-02 22:25
Thanks for your feedback, I will await version next version (0.4.5?)

**Comment by aucahuasi** [comment] 2019-10-02 22:55
@ivenzor Yep thanks!

**Comment by felipeblazing** [comment] 2019-10-05 11:08
@ivenzor the PR for this has been merged. If you build yourself you can do that. Otherwise a release will be made monday.

**Closed** 2019-10-05 11:09 UTC
Labels: bug
