### ISSUE TITLE
[BUG] Reading a file twice causes kernel to die 

### ISSUE THREAD

**Issue by VibhuJawa** [BlazingDB/pyBlazing#91] opened 2019-10-16 23:29 UTC
**Describe the bug**

When i try to read the attached table twice , it works once but fails when i try to read it again. I also checked against cudf and it seems to read that file correctly. 

The kernel seems to die with the following error:

```python
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::deallocate(): RMM_FREE: __global__ function call is not configured
Aborted (core dumped)
```

You can download the file from the url:  https://srv-file6.gofile.io/download/ywd3Ab/item.csv

**Code to reproduce bug**

```python
import os
from blazingsql import BlazingContext

bc = BlazingContext()
bc

item_result = bc.create_table('item', 
                         os.getcwd() + '/item.csv', 
                         delimiter= '|',
                         file_format = 'csv',
                         header  = None)

for i in range(0,2):
    table_result = bc.sql('select * from item limit 5').get()
    table_df = table_result.columns
    print(table_df.head(10))
    print(f"Worked {i} time")
```

Output:
```
BlazingContext ready
       0                 1           2     3                                                  4  ...        17      18       19  20                                              21
0  17820  AAAAAAAAAAAABAJK  2000-07-09  None  regular somas past the fluffy braids engage up...  ...      cyan      Oz  Unknown  57  8MJdS2aYdSydZ9Zw6llsXatytb6AUrj42owNPSpbbr0ARL
1  17821  AAAAAAAAAAAABAJL  2000-08-23  None  quiet idle hockey players would was. enticing ...  ...  metallic  Pallet  Unknown  33                   bmqB7bBbNCSJvGawoJGX25VQD24bX

[2 rows x 22 columns]
Worked 0 time
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::deallocate(): RMM_FREE: __global__ function call is not configured
Aborted (core dumped)


```

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker (Docker nightly on 16th October)

**Additional context**

This will be most probably related to the issue of reading files in a certain order discussed on slack.

**Comment by aucahuasi** [comment] 2019-10-16 23:33
Thanks @VibhuJawa for such detailed report, we will try to replicate this and get back to you when the fix is merged into develop +1

**Comment by felipeblazing** [comment] 2019-10-17 01:12
@aucahuasi i have replicateds and i think i know the issue

**Comment by felipeblazing** [comment] 2019-10-17 01:16
get_all() in DataLoader doesn't regitser the files as opened. So its not closing them

**Comment by felipeblazing** [comment] 2019-10-17 01:17
i lied yes it does still looking into it :)

**Comment by felipeblazing** [comment] 2019-10-17 01:33
It is happening in the python layer. I am going to look into this something weird is happening when its bringing result sets  into python.

**Comment by felipeblazing** [comment] 2019-10-17 11:49
So some more information. This is particularly unusual because the python library should NEVER call RMM_FREE on result sets from our queries since these all come via ipc.

**Comment by felipeblazing** [comment] 2019-10-17 11:49
I will look into it but I am guessing it has something to do with the change over to useing memory resources in RMM.

**Comment by felipeblazing** [comment] 2019-10-17 12:38
Ok so i am able to get it to work if I avoid freeing up previous result sets by keeping them in scope so something like table_results.append(table_result). The issue seems to be that cudf is trying to free the column when it has been ipcd. Looking into it

**Comment by felipeblazing** [comment] 2019-10-17 14:04
It only happens with string columns

**Comment by felipeblazing** [comment] 2019-10-22 14:27
Alright so this is how to avoid the issue for now.

you must run ```del test``` where test would be your column before setting it equal to something else.  The problem is a race condition that occurs with pythons garbage collector and the freeing of a result set.

**Closed** 2019-10-22 18:26 UTC
Labels: bug
